version: "3"
services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: registry-rs
      POSTGRES_USER: registry-rs
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8089:8080

  frontend:
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    extra_hosts:
      host.docker.internal: host-gateway
